# Generated by Django 2.1.1 on 2018-10-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default='', max_length=5)),
                ('event_name', models.CharField(default='', max_length=20)),
                ('team_name', models.CharField(default='', max_length=20)),
                ('number_of_members', models.CharField(default='', max_length=20)),
                ('member_1', models.CharField(default='', max_length=20)),
                ('member_2', models.CharField(default='', max_length=20)),
                ('member_3', models.CharField(default='', max_length=20)),
                ('member_4', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
