# Generated by Django 2.1.1 on 2018-10-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0003_auto_20181018_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robosoccer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waterrocketry',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoboSoccer',
        ),
        migrations.DeleteModel(
            name='WaterRocketry',
        ),
    ]
