# Generated by Django 2.1.1 on 2018-10-18 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='codewar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=40)),
                ('roll', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=10)),
                ('branch', models.CharField(default='', max_length=10)),
                ('section', models.CharField(default='', max_length=2)),
                ('year', models.CharField(default='', max_length=10)),
                ('event_id', models.CharField(default='', max_length=5)),
                ('event_name', models.CharField(default='', max_length=20)),
                ('team_name', models.CharField(default='', max_length=20)),
                ('number_of_members', models.CharField(default='', max_length=20)),
                ('member_1', models.CharField(default='', max_length=20)),
                ('member_2', models.CharField(default='', max_length=20)),
                ('member_3', models.CharField(default='', max_length=20)),
                ('member_4', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='karyaniti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=40)),
                ('roll', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=10)),
                ('branch', models.CharField(default='', max_length=10)),
                ('section', models.CharField(default='', max_length=2)),
                ('year', models.CharField(default='', max_length=10)),
                ('event_id', models.CharField(default='', max_length=5)),
                ('event_name', models.CharField(default='', max_length=20)),
                ('team_name', models.CharField(default='', max_length=20)),
                ('number_of_members', models.CharField(default='', max_length=20)),
                ('member_1', models.CharField(default='', max_length=20)),
                ('member_2', models.CharField(default='', max_length=20)),
                ('member_3', models.CharField(default='', max_length=20)),
                ('member_4', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mindfizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=40)),
                ('roll', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=10)),
                ('branch', models.CharField(default='', max_length=10)),
                ('section', models.CharField(default='', max_length=2)),
                ('year', models.CharField(default='', max_length=10)),
                ('event_id', models.CharField(default='', max_length=5)),
                ('event_name', models.CharField(default='', max_length=20)),
                ('team_name', models.CharField(default='', max_length=20)),
                ('number_of_members', models.CharField(default='', max_length=20)),
                ('member_1', models.CharField(default='', max_length=20)),
                ('member_2', models.CharField(default='', max_length=20)),
                ('member_3', models.CharField(default='', max_length=20)),
                ('member_4', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='waterrocketry',
            name='member_1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
