# Generated by Django 2.1.1 on 2018-10-18 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0003_auto_20181018_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cosmetics',
            new_name='Cosmetic',
        ),
    ]
