# Generated by Django 2.1.1 on 2018-10-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20181018_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrocketry',
            name='member_1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
