# Generated by Django 2.1.1 on 2018-10-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20181018_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrocketry',
            name='member_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='waterrocketry',
            name='member_3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='waterrocketry',
            name='member_4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
