# Generated by Django 2.1.1 on 2018-10-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20181018_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrocketry',
            name='event_id',
            field=models.CharField(default='ME01', max_length=5),
        ),
        migrations.AlterField(
            model_name='waterrocketry',
            name='event_name',
            field=models.CharField(default='WATER ROCKETRY', max_length=20),
        ),
    ]
