# Generated by Django 2.1.1 on 2018-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20181019_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='member_1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='member_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
