# Generated by Django 2.1.1 on 2018-10-20 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0009_auto_20181019_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUBG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=40)),
                ('roll', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=10)),
                ('branch', models.CharField(default='', max_length=10)),
                ('section', models.CharField(default='', max_length=2)),
                ('year', models.CharField(default='', max_length=10)),
                ('event_id', models.CharField(default='PUBG', max_length=5)),
                ('event_name', models.CharField(default='PUBG', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='startupmaster',
            name='user',
        ),
        migrations.DeleteModel(
            name='StartUpMaster',
        ),
    ]
